### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by midgithub** [TaleLin/lin-cms-vue#463]
**重现步骤（可选）：**
最新版
编译前后端后,后端使用koa,正常登录后
1. 头像显示不出来
2. 修改头像,报超时.
3. 修改缩略后的tooltip的样式 我看在element-variable.scss中有写但是又注释掉了.打开注释后发现 after部分暂时没找到方法修改颜色.只能注释回去.
**期望的结果是什么？**
正常显示头像,修改头像,修改tooltip样式
**实际的结果是什么？**

**Comment by vanoneang** [comment]
我刚用 master 分支跑了下代码，头像正常显示，修改也没有问题。

1. 检查一下头像部分的URL是否正常；
2. 修改头像就是图片上传接口，Debug一下是哪一步出现了什么问题；
3. 没看明白什么意思。

**Comment by midgithub** [comment]
多谢大大即时迅速的回答! 
问题3补充一个图.
![image](https://user-images.githubusercontent.com/20261416/119252418-ba707c80-bbde-11eb-879b-1e253548670c.png).  黑色的小尾巴想要也改成绿的
1. 2. 我再自己是试试.

**Comment by vanoneang** [comment]
```css
.el-tooltip {
  padding-left: 16px !important;
  line-height: 48px;
  height: 50px;
}

.el-tooltip__popper.is-dark {
  background: red !important;
}
.el-tooltip__popper[x-placement^=right] .popper__arrow:after{
  border-right-color:  red !important;
}
```

大概这样，试下看看
